export type Orientation = "N" | "NE" | "E" | "SE" | "S" | "SW" | "W" | "NW";
export type Municipality = "Maó" | "Ciutadella" | "Alaior" | "Es Mercadal" | "Ferreries" | "Sant Lluís" | "Es Castell" | "Es Migjorn Gran" | "Menorca";
export type BeachType = "Familiar" | "Virgen" | "Nudista" | "Kitesurf" | "Surf" | "Tranquila" | "Urbana";

export interface Beach {
  name: string;
  orientation: Orientation;
  municipality: Municipality;
  length: string;
  lengthM: number;
  type: BeachType;
  description: string;
  descriptionCa: string;
  descriptionEn: string;
  descriptionFr: string;
  parking: boolean;
  services: string[];
  lat: number;
  lon: number;
}

export const OPPOSITE_ORIENTATIONS: Record<Orientation, Orientation[]> = {
  N:  ["S", "SW", "SE"],
  NE: ["SW", "S",  "W"],
  E:  ["W",  "SW", "NW"],
  SE: ["NW", "N",  "W"],
  S:  ["N",  "NW", "NE"],
  SW: ["NE", "N",  "E"],
  W:  ["E",  "SE", "NE"],
  NW: ["SE", "S",  "E"],
};

export const WIND_NAMES: Record<Orientation, string> = {
  N: "Tramuntana", NE: "Gregal", E: "Llevant", SE: "Xaloc",
  S: "Migjorn", SW: "Llebeig", W: "Ponent", NW: "Mestral",
};

export const MUNICIPALITIES: Municipality[] = [
  "Maó", "Ciutadella", "Alaior", "Es Mercadal", "Ferreries", "Sant Lluís", "Es Castell", "Es Migjorn Gran"
];

export const BEACH_TYPES: BeachType[] = [
  "Familiar", "Virgen", "Nudista", "Kitesurf", "Surf", "Tranquila", "Urbana"
];

export const ALL_SERVICES = ["Chiringuito", "Salvamento", "Parking", "Duchas", "Accesible", "Kayak", "Escuela kite"];

export function distanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a = Math.sin(dLat/2)**2 + Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
}

export const BEACHES: Beach[] = [
  {
    name: "Arenal d'en Castell",
    orientation: "N", municipality: "Es Mercadal",
    length: "500 m", lengthM: 500, type: "Familiar",
    description: "Bahía en herradura perfectamente cerrada, muy segura para niños. Aguas calmadas y poco profundas con todos los servicios.",
    descriptionCa: "Badia en ferradura perfectament tancada, molt segura per a nens. Aigües calmades i poc fondes amb tots els serveis.",
    descriptionEn: "Perfectly enclosed horseshoe bay, very safe for children. Calm, shallow waters with all services.",
    descriptionFr: "Baie en fer à cheval parfaitement fermée, très sûre pour les enfants. Eaux calmes et peu profondes avec tous les services.",
    parking: true, services: ["Chiringuito", "Salvamento", "Duchas", "Parking"],
    lat: 40.02193277115611, lon: 4.182275929773778,
  },
  {
    name: "Banyuls",
    orientation: "SE", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.92942764796674, lon: 3.8920705121354464,
  },
  {
    name: "Binibeca Nou",
    orientation: "E", municipality: "Sant Lluís",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.816442605203015, lon: 4.240070866122622,
  },
  {
    name: "Binigaus",
    orientation: "SE", municipality: "Es Migjorn Gran",
    length: "700 m", lengthM: 700, type: "Nudista",
    description: "Playa nudista larga y salvaje, solo accesible a pie (20 min). Sin servicios pero con una soledad y naturaleza difícil de superar.",
    descriptionCa: "Platja nudista llarga i salvatge, només accessible a peu (20 min). Sense serveis però amb una solitud i natura difícil de superar.",
    descriptionEn: "Long wild nudist beach, only accessible on foot (20 min). No services but unbeatable solitude and nature.",
    descriptionFr: "Longue plage nudiste sauvage, accessible uniquement à pied (20 min). Sans services mais une solitude et une nature incomparables.",
    parking: false, services: [],
    lat: 39.92195341177989, lon: 4.024419415500063,
  },
  {
    name: "Binimel·La",
    orientation: "NE", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.05170509124282, lon: 4.053169489785361,
  },
  {
    name: "Binisafuller",
    orientation: "SE", municipality: "Sant Lluís",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.82899164074996, lon: 4.218714038871804,
  },
  {
    name: "Cala Alcaufar",
    orientation: "SE", municipality: "Sant Lluís",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.82897474107289, lon: 4.292580413599559,
  },
  {
    name: "Cala Barril",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.06225902424815, lon: 4.028943498345763,
  },
  {
    name: "Cala Binidali",
    orientation: "SE", municipality: "Maó",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.8345931414252, lon: 4.198071909780637,
  },
  {
    name: "Cala Blanca",
    orientation: "SW", municipality: "Ciutadella",
    length: "300 m", lengthM: 300, type: "Familiar",
    description: "Arena blanca y aguas de color azul intenso cerca de Ciutadella. Atardeceres espectaculares. Muy popular entre locales.",
    descriptionCa: "Sorra blanca i aigües de color blau intens prop de Ciutadella. Capvespres espectaculars. Molt popular entre locals.",
    descriptionEn: "White sand and intensely blue water near Ciutadella. Spectacular sunsets. Very popular with locals.",
    descriptionFr: "Sable blanc et eau d'un bleu intense près de Ciutadella. Couchers de soleil spectaculaires. Très populaire parmi les locaux.",
    parking: true, services: ["Chiringuito", "Duchas", "Parking"],
    lat: 39.967645170030934, lon: 3.835635159079723,
  },
  {
    name: "Cala Blanes",
    orientation: "S", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Urbana",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.0007287684141, lon: 3.8133555157936883,
  },
  {
    name: "Cala Bosch",
    orientation: "E", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Familiar",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.926652840761164, lon: 3.8374058207834083,
  },
  {
    name: "Cala Brut",
    orientation: "SE", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.000821614883776, lon: 3.8068291597488315,
  },
  {
    name: "Cala Carbó",
    orientation: "N", municipality: "Es Mercadal",
    length: "150 m", lengthM: 150, type: "Tranquila",
    description: "Mini cala de aguas extraordinariamente calmadas, ideal para snorkel. Muy recogida entre acantilados, poca gente incluso en verano.",
    descriptionCa: "Mini cala d'aigües extraordinàriament calmades, ideal per fer snorkel. Molt recollida entre penya-segats, poca gent fins i tot a l'estiu.",
    descriptionEn: "Mini cove with extraordinarily calm waters, ideal for snorkelling. Very sheltered between cliffs, few people even in summer.",
    descriptionFr: "Mini crique aux eaux extraordinairement calmes, idéale pour le snorkeling. Très abritée entre les falaises, peu de monde même en été.",
    parking: false, services: [],
    lat: 40.059052885168725, lon: 3.9311131513487605,
  },
  {
    name: "Cala Degolladors",
    orientation: "SW", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.994355034051445, lon: 3.8353098876717673,
  },
  {
    name: "Cala En Calderer",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.055661676732214, lon: 4.016276275156525,
  },
  {
    name: "Cala En Cavaller",
    orientation: "NE", municipality: "Maó",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.97882013996915, lon: 4.258941958509905,
  },
  {
    name: "Cala Escorxada",
    orientation: "SE", municipality: "Es Migjorn Gran",
    length: "200 m", lengthM: 200, type: "Virgen",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.9256832120625, lon: 4.004496325663781,
  },
  {
    name: "Cala Forcat",
    orientation: "SE", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.99939963354738, lon: 3.799799328707093,
  },
  {
    name: "Cala Fustam",
    orientation: "SE", municipality: "Es Migjorn Gran",
    length: "200 m", lengthM: 200, type: "Virgen",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.92639518606, lon: 4.000824163556244,
  },
  {
    name: "Cala Galdana",
    orientation: "SW", municipality: "Ferreries",
    length: "400 m", lengthM: 400, type: "Familiar",
    description: "La 'reina de las calas'. Bahía semicircular perfecta rodeada de acantilados y pinos. Aguas muy calmadas, ideal para familias con niños.",
    descriptionCa: "La 'reina de les cales'. Badia semicircular perfecta envoltada de penya-segats i pins. Aigües molt calmades, ideal per a famílies amb nens.",
    descriptionEn: "The 'queen of the coves'. Perfect semicircular bay surrounded by cliffs and pines. Very calm waters, ideal for families with children.",
    descriptionFr: "La 'reine des criques'. Baie semi-circulaire parfaite entourée de falaises et de pins. Eaux très calmes, idéale pour les familles.",
    parking: true, services: ["Chiringuito", "Salvamento", "Kayak", "Duchas", "Parking"],
    lat: 39.93846132101672, lon: 3.959776272778295,
  },
  {
    name: "Cala Llucalari",
    orientation: "N", municipality: "Alaior",
    length: "200 m", lengthM: 200, type: "Virgen",
    description: "Cala virgen accesible por el Camí de Cavalls. Aguas cristalinas y entorno natural protegido. Sin servicios, perfecta para escapar.",
    descriptionCa: "Cala verge accessible pel Camí de Cavalls. Aigües cristal·lines i entorn natural protegit. Sense serveis, perfecta per escapar.",
    descriptionEn: "Wild cove accessible via the Camí de Cavalls. Crystal-clear waters and protected natural setting. No services, perfect for escaping.",
    descriptionFr: "Crique sauvage accessible par le Camí de Cavalls. Eaux cristallines et cadre naturel protégé. Sans services, parfaite pour s'échapper.",
    parking: false, services: [],
    lat: 39.89141191024622, lon: 4.082163737023877,
  },
  {
    name: "Cala Macarella",
    orientation: "S", municipality: "Ferreries",
    length: "500 m", lengthM: 500, type: "Virgen",
    description: "Una de las calas más espectaculares de Menorca. Acantilados blancos, pinos centenarios y agua de color esmeralda que quita el aliento.",
    descriptionCa: "Una de les cales més espectaculars de Menorca. Penya-segats blancs, pins centenaris i una aigua de color esmeralda que impressiona.",
    descriptionEn: "One of Menorca's most spectacular coves. White cliffs, ancient pines and breathtaking emerald-coloured water.",
    descriptionFr: "L'une des criques les plus spectaculaires de Minorque. Falaises blanches, pins centenaires et eau émeraude à couper le souffle.",
    parking: false, services: ["Chiringuito"],
    lat: 39.93874021687721, lon: 3.937222160400047,
  },
  {
    name: "Cala Macarelleta",
    orientation: "SW", municipality: "Ferreries",
    length: "200 m", lengthM: 200, type: "Nudista",
    description: "Pequeña cala nudista gemela de Macarella, a 10 minutos a pie. Muy recogida y tranquila con el mismo agua espectacular.",
    descriptionCa: "Petita cala nudista bessona de Macarella, a 10 minuts a peu. Molt recollida i tranquil·la amb la mateixa aigua espectacular.",
    descriptionEn: "Small nudist cove twin of Macarella, 10 minutes on foot. Very sheltered and quiet with the same spectacular water.",
    descriptionFr: "Petite crique nudiste jumelle de Macarella, à 10 minutes à pied. Très abritée et tranquille avec les mêmes eaux spectaculaires.",
    parking: false, services: [],
    lat: 39.93639460945966, lon: 3.9348196100051767,
  },
  {
    name: "Cala Mesquida",
    orientation: "E", municipality: "Maó",
    length: "400 m", lengthM: 400, type: "Surf",
    description: "Playa abierta con oleaje frecuente, favorita de surfistas. Arena dorada, dunas y entorno natural bien conservado cerca de Maó.",
    descriptionCa: "Platja oberta amb onatge freqüent, favorita de surfistes. Sorra daurada, dunes i entorn natural ben conservat prop de Maó.",
    descriptionEn: "Open beach with frequent waves, favourite of surfers. Golden sand, dunes and well-preserved natural setting near Maó.",
    descriptionFr: "Plage ouverte avec des vagues fréquentes, préférée des surfeurs. Sable doré, dunes et cadre naturel bien préservé près de Maó.",
    parking: true, services: ["Parking"],
    lat: 39.916145693007536, lon: 4.286758498028426,
  },
  {
    name: "Cala Mica",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.05668727808843, lon: 4.067134551593464,
  },
  {
    name: "Cala Mitjana",
    orientation: "S", municipality: "Ferreries",
    length: "350 m", lengthM: 350, type: "Virgen",
    description: "Cala virgen preciosa accesible a pie desde Cala Galdana (20 min). Aguas turquesas y poca gente comparado con su vecina.",
    descriptionCa: "Cala verge preciosa accessible a peu des de Cala Galdana (20 min). Aigües turqueses i poca gent comparat amb la seva veïna.",
    descriptionEn: "Beautiful wild cove accessible on foot from Cala Galdana (20 min). Turquoise waters and fewer people than its neighbour.",
    descriptionFr: "Belle crique sauvage accessible à pied depuis Cala Galdana (20 min). Eaux turquoises et moins de monde que sa voisine.",
    parking: false, services: [],
    lat: 39.93448229950134, lon: 3.972353698185594,
  },
  {
    name: "Cala Morell",
    orientation: "N", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Cala escondida de roca calcárea blanca con agua turquesa. Ambiente muy tranquilo y local. Junto a un yacimiento prehistórico.",
    descriptionCa: "Cala amagada de roca calcària blanca amb aigua turquesa. Ambient molt tranquil i local. Al costat d'un jaciment prehistòric.",
    descriptionEn: "Hidden cove with white limestone rock and turquoise water. Very quiet and local atmosphere. Next to a prehistoric site.",
    descriptionFr: "Crique cachée avec roches calcaires blanches et eau turquoise. Ambiance très locale et tranquille. À côté d'un site préhistorique.",
    parking: false, services: [],
    lat: 40.05324897555333, lon: 3.8825046788373263,
  },
  {
    name: "Cala Morella Nou",
    orientation: "NE", municipality: "Maó",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.98320018312329, lon: 4.258001824539728,
  },
  {
    name: "Cala Pedrera",
    orientation: "N", municipality: "Es Castell",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.87480770568025, lon: 4.295351691049455,
  },
  {
    name: "Cala Pilar",
    orientation: "N", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Nudista",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.05136033740839, lon: 3.9784305093740744,
  },
  {
    name: "Cala Pregonda",
    orientation: "N", municipality: "Es Mercadal",
    length: "500 m", lengthM: 500, type: "Virgen",
    description: "Joya escondida con arena de color rojizo única en Menorca. Rodeada de islotes y dunas. Solo accesible a pie (40 min) o en barco.",
    descriptionCa: "Joia amagada amb sorra de color vermellós única a Menorca. Envoltada d'illots i dunes. Només accessible a peu (40 min) o en barca.",
    descriptionEn: "Hidden gem with uniquely reddish sand. Surrounded by islets and dunes. Only accessible on foot (40 min) or by boat.",
    descriptionFr: "Joyau caché au sable rougeâtre unique à Minorque. Entourée d'îlots et de dunes. Accessible uniquement à pied (40 min) ou en bateau.",
    parking: false, services: [],
    lat: 40.05714773996698, lon: 4.040478628671451,
  },
  {
    name: "Cala Pudent",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.04355752278602, lon: 4.15870465977858,
  },
  {
    name: "Cala Tirant",
    orientation: "N", municipality: "Es Mercadal",
    length: "600 m", lengthM: 600, type: "Kitesurf",
    description: "Playa favorita de kitesurfistas y windsurfistas gracias a sus vientos constantes. Arena clara y aguas poco profundas.",
    descriptionCa: "Platja favorita de kitesurfistes i windsurfistes gràcies als seus vents constants. Sorra clara i aigües poc fondes.",
    descriptionEn: "Favourite beach for kitesurf and windsurf lovers thanks to its constant winds. Light sand and shallow waters.",
    descriptionFr: "Plage préférée des kitesurfeurs et windsurfeurs grâce à ses vents constants. Sable clair et eaux peu profondes.",
    parking: true, services: ["Escuela kite", "Parking"],
    lat: 40.04505599096925, lon: 4.1032635708809755,
  },
  {
    name: "Cala Turqueta",
    orientation: "SE", municipality: "Ciutadella",
    length: "300 m", lengthM: 300, type: "Virgen",
    description: "Cala virgen de aguas extraordinariamente transparentes en tonos azul y verde. Rodeada de pinos con arena blanca y fina.",
    descriptionCa: "Cala verge d'aigües extraordinàriament transparents en tons blau i verd. Envoltada de pins amb sorra blanca i fina.",
    descriptionEn: "Wild cove with extraordinarily clear blue-green waters. Surrounded by pines with fine white sand.",
    descriptionFr: "Crique sauvage aux eaux extraordinairement transparentes bleu-vert. Entourée de pins avec du sable blanc et fin.",
    parking: false, services: [],
    lat: 39.93256989667136, lon: 3.9148346340249405,
  },
  {
    name: "Cala Viola de Llevant",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.07455385794231, lon: 4.09330878092512,
  },
  {
    name: "Cala Viola de Ponent",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.07624696787266, lon: 4.090717202778368,
  },
  {
    name: "Cala de Sa Torreta",
    orientation: "NE", municipality: "Maó",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.96414245986037, lon: 4.255657934606342,
  },
  {
    name: "Cala de Sant Llorenç",
    orientation: "S", municipality: "Alaior",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.88316991174337, lon: 4.0937143423034845,
  },
  {
    name: "Cala en Blanes",
    orientation: "S", municipality: "Ciutadella",
    length: "400 m", lengthM: 400, type: "Urbana",
    description: "Cala urbana bien equipada con todos los servicios a pie de playa. Muy práctica con paseo marítimo y restaurantes cerca.",
    descriptionCa: "Cala urbana ben equipada amb tots els serveis a peu de platja. Molt pràctica amb passeig marítim i restaurants a prop.",
    descriptionEn: "Well-equipped urban cove with all services at the beach. Very practical with promenade and nearby restaurants.",
    descriptionFr: "Crique urbaine bien équipée avec tous les services sur la plage. Très pratique avec promenade et restaurants à proximité.",
    parking: true, services: ["Chiringuito", "Salvamento", "Duchas", "Parking"],
    lat: 40.00098307072547, lon: 3.813524979811635,
  },
  {
    name: "Cala en Porter",
    orientation: "S", municipality: "Alaior",
    length: "350 m", lengthM: 350, type: "Familiar",
    description: "Espectacular cala entre acantilados de 40 metros de altura. Arena fina y aguas de colores increíbles. Urbanización encima con vistas únicas.",
    descriptionCa: "Espectacular cala entre penya-segats de 40 metres d'alçada. Sorra fina i aigües de colors increïbles. Urbanització a sobre amb vistes úniques.",
    descriptionEn: "Spectacular cove between 40-metre-high cliffs. Fine sand and incredible water colours. Development above with unique views.",
    descriptionFr: "Crique spectaculaire entre des falaises de 40 mètres. Sable fin et couleurs d'eau incroyables. Urbanisation au-dessus avec des vues uniques.",
    parking: true, services: ["Chiringuito", "Salvamento", "Duchas", "Parking"],
    lat: 39.87124713909658, lon: 4.131879255631261,
  },
  {
    name: "Cales Coves",
    orientation: "N", municipality: "Alaior",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.86497497557643, lon: 4.144257094877818,
  },
  {
    name: "Cales Piques",
    orientation: "SW", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.00356782257885, lon: 3.798419724678865,
  },
  {
    name: "Calo Blanc",
    orientation: "NE", municipality: "Sant Lluís",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.82934813339386, lon: 4.2110089812004485,
  },
  {
    name: "Cavalleria",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.05990153094756, lon: 4.076887975673746,
  },
  {
    name: "D'En Gorries",
    orientation: "SW", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.98164220126111, lon: 3.8345260553383484,
  },
  {
    name: "D'En Tortuga",
    orientation: "NE", municipality: "Maó",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.988731065408494, lon: 4.255202387637449,
  },
  {
    name: "D'Es Tamarells",
    orientation: "NE", municipality: "Maó",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.95848064632206, lon: 4.262830764783983,
  },
  {
    name: "De Ferragut",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.05990153094756, lon: 4.076887975673746,
  },
  {
    name: "De Fornells",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.05648711828278, lon: 4.132667156625613,
  },
  {
    name: "Des Bot",
    orientation: "SE", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.049655816547364, lon: 3.924752823094326,
  },
  {
    name: "Es Canutells",
    orientation: "SE", municipality: "Maó",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.85276469632616, lon: 4.1682193965586265,
  },
  {
    name: "Es Grau",
    orientation: "NE", municipality: "Maó",
    length: "600 m", lengthM: 600, type: "Familiar",
    description: "Playa dentro del Parc Natural de s'Albufera. Aguas muy poco profundas y calmadas, perfectas para niños. Entorno natural protegido único.",
    descriptionCa: "Platja dins del Parc Natural de s'Albufera. Aigües molt poc fondes i calmades, perfectes per a nens. Entorn natural protegit únic.",
    descriptionEn: "Beach within the s'Albufera Natural Park. Very shallow, calm waters perfect for children. Unique protected natural setting.",
    descriptionFr: "Plage dans le Parc Naturel de s'Albufera. Eaux très peu profondes et calmes, parfaites pour les enfants. Cadre naturel protégé unique.",
    parking: true, services: ["Chiringuito", "Parking"],
    lat: 39.94982664663073, lon: 4.266206381521211,
  },
  {
    name: "Es Macar D'En Tosqueta",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.05809318587006, lon: 4.1646608936301215,
  },
  {
    name: "Es Tancats",
    orientation: "N", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.04623041600606, lon: 3.922752987886372,
  },
  {
    name: "Ets Alocs",
    orientation: "NW", municipality: "Ferreries",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.05220656871487, lon: 3.987048742947685,
  },
  {
    name: "Na Macaret",
    orientation: "N", municipality: "Es Mercadal",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 40.01608963339182, lon: 4.200305274077732,
  },
  {
    name: "Punta Prima",
    orientation: "E", municipality: "Sant Lluís",
    length: "300 m", lengthM: 300, type: "Familiar",
    description: "Playa con vistas privilegiadas al islote de l'Aire y su faro. Aguas cristalinas y arena fina. Bien equipada y fácil de acceder.",
    descriptionCa: "Platja amb vistes privilegiades a l'illot de l'Aire i el seu far. Aigües cristal·lines i sorra fina. Ben equipada i fàcil d'accedir.",
    descriptionEn: "Beach with privileged views of the Aire islet and its lighthouse. Crystal-clear waters and fine sand. Well equipped and easy to reach.",
    descriptionFr: "Plage avec vue privilégiée sur l'îlot de l'Aire et son phare. Eaux cristallines et sable fin. Bien équipée et facile d'accès.",
    parking: true, services: ["Chiringuito", "Salvamento", "Duchas", "Parking"],
    lat: 39.813960425058504, lon: 4.28028860095154,
  },
  {
    name: "Rinco Fondu",
    orientation: "S", municipality: "Sant Lluís",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.82308107785766, lon: 4.225911616270957,
  },
  {
    name: "Sa Farola",
    orientation: "SW", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.998044500580654, lon: 3.822381691042903,
  },
  {
    name: "Sant Adeodato",
    orientation: "SE", municipality: "Es Migjorn Gran",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.916887402509815, lon: 4.033682424302221,
  },
  {
    name: "Sant Tomas",
    orientation: "SE", municipality: "Es Migjorn Gran",
    length: "1.2 km", lengthM: 1200, type: "Familiar",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: true, services: ["Chiringuito", "Salvamento", "Duchas", "Parking"],
    lat: 39.91367038878966, lon: 4.041978620597302,
  },
  {
    name: "Santandria",
    orientation: "W", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Familiar",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: true, services: ["Chiringuito", "Salvamento", "Duchas", "Parking"],
    lat: 39.97848556119102, lon: 3.8393377438015386,
  },
  {
    name: "Son Bou",
    orientation: "SE", municipality: "Alaior",
    length: "2.5 km", lengthM: 2500, type: "Familiar",
    description: "La playa más larga de Menorca con 2.5 km. Arena fina, aguas poco profundas y todos los servicios. Perfecta para familias.",
    descriptionCa: "La platja més llarga de Menorca amb 2.5 km. Sorra fina, aigües poc fondes i tots els serveis. Perfecta per a famílies.",
    descriptionEn: "Menorca's longest beach at 2.5 km. Fine sand, shallow waters and all services. Perfect for families.",
    descriptionFr: "La plus longue plage de Minorque avec 2,5 km. Sable fin, eaux peu profondes et tous les services. Parfaite pour les familles.",
    parking: true, services: ["Chiringuito", "Salvamento", "Accesible", "Duchas", "Parking"],
    lat: 39.89969760608061, lon: 4.072221270626053,
  },
  {
    name: "Son Parc",
    orientation: "N", municipality: "Es Mercadal",
    length: "600 m", lengthM: 600, type: "Familiar",
    description: "Amplia playa en bahía natural con aguas calmadas. Rodeada de pinos y con dunas. Muy tranquila, ideal para familias que buscan espacio.",
    descriptionCa: "Àmplia platja en badia natural amb aigües calmades. Envoltada de pins i amb dunes. Molt tranquil·la, ideal per a famílies.",
    descriptionEn: "Wide beach in a natural bay with calm waters. Surrounded by pines and dunes. Very quiet, ideal for families looking for space.",
    descriptionFr: "Large plage dans une baie naturelle aux eaux calmes. Entourée de pins et de dunes. Très tranquille, idéale pour les familles.",
    parking: true, services: ["Chiringuito", "Salvamento", "Parking"],
    lat: 40.03447192236396, lon: 4.161002572381256,
  },
  {
    name: "Son Saura",
    orientation: "S", municipality: "Ciutadella",
    length: "800 m", lengthM: 800, type: "Virgen",
    description: "Doble cala virgen rodeada de pinos. Aguas cristalinas de color turquesa intenso. Acceso por pista de tierra, de gran belleza.",
    descriptionCa: "Doble cala verge envoltada de pins. Aigües cristal·lines de color turquesa intens. Accés per pista de terra, de gran bellesa.",
    descriptionEn: "Double wild cove surrounded by pine trees. Crystal-clear, intensely turquoise waters. Accessed by dirt track, stunning beauty.",
    descriptionFr: "Double crique sauvage entourée de pins. Eaux cristallines d'un turquoise intense. Accès par piste de terre, d'une grande beauté.",
    parking: false, services: [],
    lat: 39.928053676303946, lon: 3.8921195710755003,
  },
  {
    name: "Son Xoriguer",
    orientation: "SE", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Familiar",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.925974645448406, lon: 3.844730288310415,
  },
  {
    name: "Talaier",
    orientation: "SE", municipality: "Ciutadella",
    length: "200 m", lengthM: 200, type: "Virgen",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.92700768809841, lon: 3.90273418376328,
  },
  {
    name: "Talis",
    orientation: "SE", municipality: "Es Migjorn Gran",
    length: "200 m", lengthM: 200, type: "Tranquila",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.90763706543249, lon: 4.054378283818248,
  },
  {
    name: "Trebaluger",
    orientation: "SE", municipality: "Es Migjorn Gran",
    length: "200 m", lengthM: 200, type: "Virgen",
    description: "Playa o cala con aguas limpias y entorno natural característico de Menorca.",
    descriptionCa: "Platja o cala amb aigües netes i entorn natural característic de Menorca.",
    descriptionEn: "Beach or cove with clean waters and natural setting characteristic of Menorca.",
    descriptionFr: "Plage ou crique aux eaux propres et cadre naturel caractéristique de Minorque.",
    parking: false, services: [],
    lat: 39.93230496760924, lon: 3.989332644272806,
  },
];
